[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm run build"]
# cache-bust: 2026-03-05-v2

[start]
cmd = "node dist/standalone.js"
