/**
 * Catálogo completo de produtos ZUNO GLASS
 * Baseado no pedido #54864 - 32 produtos
 * Imagens: fotos locais em /images/products/
 */

export interface ProductVariant {
  color: string;
  colorName: string;
  image: string;
}

export interface CatalogProduct {
  id: string;
  name: string;
  tagline: string;
  price: number;
  description: string;
  features: string[];
  image: string;
  category: 'performance' | 'lifestyle';
  variants: ProductVariant[];
  isNew?: boolean;
  stock?: number;
}

// Base path for local product images
const IMG = '/images/products/';

export const catalog: CatalogProduct[] = [
  // === LINHA PERFORMANCE ===
  {
    id: 'zuno-prime-preto-fosco',
    name: 'ZUNO PRIME PRETO FOSCO',
    tagline: 'INVISÍVEL. IMPARÁVEL.',
    price: 189.90,
    description: 'Armação esportiva máscara de perfil baixo para máxima aerodinâmica. Lentes preto fosco com proteção UV400 para treinos de alta intensidade.',
    features: ['Lentes Preto Fosco', 'Armação Máscara', 'Grip Antiderrapante', 'Proteção UV400'],
    image: `${IMG}Prime  Preto Fosco.webp`,
    category: 'performance',
    variants: [
      { color: '#1a1a1a', colorName: 'Preto Fosco', image: `${IMG}Prime  Preto Fosco.webp` },
    ],
    isNew: true,
    stock: 8,
  },
  {
    id: 'zuno-prime-azul-multicolors',
    name: 'ZUNO PRIME AZUL MULTICOLORS',
    tagline: 'INVISÍVEL. IMPARÁVEL.',
    price: 189.90,
    description: 'Armação esportiva máscara com lentes azul multicolors espelhadas. Alta performance para corridas e treinos ao ar livre.',
    features: ['Lentes Azul Multicolors', 'Armação Máscara', 'Grip Antiderrapante', 'Proteção UV400'],
    image: `${IMG}Prime  Azul Multicolors Preto.webp`,
    category: 'performance',
    variants: [
      { color: '#2563eb', colorName: 'Azul Multicolors Preto', image: `${IMG}Prime  Azul Multicolors Preto.webp` },
    ],
    isNew: true,
    stock: 4,
  },
  {
    id: 'zuno-prime-verde-multicolors',
    name: 'ZUNO PRIME VERDE MULTICOLORS',
    tagline: 'INVISÍVEL. IMPARÁVEL.',
    price: 189.90,
    description: 'Armação esportiva máscara com lentes verde multicolors. Máxima visibilidade para treinos de alta intensidade.',
    features: ['Lentes Verde Multicolors', 'Armação Máscara', 'Grip Antiderrapante', 'Proteção UV400'],
    image: `${IMG}Prime   Verde Multicolors Cinza Azul.webp`,
    category: 'performance',
    variants: [
      { color: '#16a34a', colorName: 'Verde Multicolors Cinza Azul', image: `${IMG}Prime   Verde Multicolors Cinza Azul.webp` },
    ],
    isNew: true,
    stock: 4,
  },
  {
    id: 'zuno-prime-amarelo-multicolors',
    name: 'ZUNO PRIME AMARELO MULTICOLORS',
    tagline: 'INVISÍVEL. IMPARÁVEL.',
    price: 189.90,
    description: 'Armação esportiva máscara com lentes amarelo multicolors de alto contraste. Ideal para ciclismo e corrida.',
    features: ['Lentes Amarelo Multicolors', 'Armação Máscara', 'Grip Antiderrapante', 'Proteção UV400'],
    image: `${IMG}Prime Amarelo Multicolors Branco Preto.webp`,
    category: 'performance',
    variants: [
      { color: '#eab308', colorName: 'Amarelo Multicolors Branco Preto', image: `${IMG}Prime Amarelo Multicolors Branco Preto.webp` },
    ],
    isNew: true,
    stock: 4,
  },
  {
    id: 'zuno-devon-preto-fosco',
    name: 'ZUNO DEVON PRETO FOSCO',
    tagline: 'DOMINE O TERRENO.',
    price: 189.90,
    description: 'Óculos esportivo máscara Devon com armação injetada e lentes preto fosco. Design agressivo para quem não para.',
    features: ['Lentes Preto Fosco', 'Armação Injetada', 'Proteção UV400', 'Armação Flexível'],
    image: `${IMG}Devon  Preto Fosco.webp`,
    category: 'performance',
    variants: [
      { color: '#1a1a1a', colorName: 'Preto Fosco', image: `${IMG}Devon  Preto Fosco.webp` },
    ],
    isNew: true,
    stock: 2,
  },
  {
    id: 'zuno-devon-azul-multicolors',
    name: 'ZUNO DEVON AZUL MULTICOLORS',
    tagline: 'DOMINE O TERRENO.',
    price: 189.90,
    description: 'Óculos esportivo máscara Devon com lentes azul multicolors transparente cinza. Estilo e performance em um só.',
    features: ['Lentes Azul Multicolors', 'Armação Injetada', 'Proteção UV400', 'Armação Flexível'],
    image: `${IMG}Devon  Azul Multicolors Transparente Cinza.webp`,
    category: 'performance',
    variants: [
      { color: '#2563eb', colorName: 'Azul Multicolors Transparente Cinza', image: `${IMG}Devon  Azul Multicolors Transparente Cinza.webp` },
    ],
    isNew: true,
    stock: 4,
  },
  {
    id: 'zuno-devon-marrom-verde',
    name: 'ZUNO DEVON MARROM VERDE',
    tagline: 'DOMINE O TERRENO.',
    price: 189.90,
    description: 'Óculos esportivo máscara Devon com lentes marrom verde. Para quem busca performance com estilo único.',
    features: ['Lentes Marrom Verde', 'Armação Injetada', 'Proteção UV400', 'Armação Flexível'],
    image: `${IMG}Devon  Marrom Verde.webp`,
    category: 'performance',
    variants: [
      { color: '#92400e', colorName: 'Marrom Verde', image: `${IMG}Devon  Marrom Verde.webp` },
    ],
    isNew: true,
    stock: 5,
  },
  {
    id: 'zuno-madagascar-azul-escuro',
    name: 'ZUNO MADAGASCAR AZUL ESCURO',
    tagline: 'VELOCIDADE SELVAGEM.',
    price: 189.90,
    description: 'Óculos esportivo Madagascar com lentes azul escuro preto. Lentes polarizadas de alta definição para máxima clareza visual.',
    features: ['Lentes Azul Escuro Preto', 'Armação Injetada', 'Proteção UV400', 'Antirreflexo'],
    image: `${IMG}Madagascar Azul Escuro Preto.webp`,
    category: 'performance',
    variants: [
      { color: '#1e40af', colorName: 'Azul Escuro Preto', image: `${IMG}Madagascar Azul Escuro Preto.webp` },
    ],
    stock: 4,
  },
  {
    id: 'zuno-madagascar-verde-preto',
    name: 'ZUNO MADAGASCAR VERDE PRETO',
    tagline: 'VELOCIDADE SELVAGEM.',
    price: 189.90,
    description: 'Óculos esportivo Madagascar com lentes verde preto. Alta performance para treinos ao ar livre.',
    features: ['Lentes Verde Preto', 'Armação Injetada', 'Proteção UV400', 'Antirreflexo'],
    image: `${IMG}Madagascar Verde Preto.webp`,
    category: 'performance',
    variants: [
      { color: '#16a34a', colorName: 'Verde Preto', image: `${IMG}Madagascar Verde Preto.webp` },
    ],
    stock: 3,
  },
  {
    id: 'zuno-infinity-prata-espelhado',
    name: 'ZUNO INFINITY PRATA ESPELHADO',
    tagline: 'REFLEXO INFINITO.',
    price: 189.90,
    description: 'Óculos esportivo Infinity com lentes prata espelhado preto. Design futurista para quem está sempre à frente.',
    features: ['Lentes Prata Espelhado', 'Armação Injetada', 'Proteção UV400', 'Design Futurista'],
    image: `${IMG}Infinity  Prata Espelhado Preto.webp`,
    category: 'performance',
    variants: [
      { color: '#c0c0c0', colorName: 'Prata Espelhado Preto', image: `${IMG}Infinity  Prata Espelhado Preto.webp` },
    ],
    isNew: true,
    stock: 3,
  },
  {
    id: 'zuno-jin-preto-verde',
    name: 'ZUNO JIN PRETO VERDE',
    tagline: 'FLUIDEZ EM MOVIMENTO.',
    price: 189.90,
    description: 'Óculos esportivo máscara Jin com lentes preto/verde. Armação ultraleve para treinos longos sem desconforto.',
    features: ['Lentes Preto Verde', 'Ultra Leve', 'Ventilação Avançada', 'Grip Premium'],
    image: `${IMG}Jin  Preto Verde.webp`,
    category: 'performance',
    variants: [
      { color: '#1a1a1a', colorName: 'Preto Verde', image: `${IMG}Jin  Preto Verde.webp` },
    ],
    stock: 2,
  },
  {
    id: 'zuno-jin-branco-rosa',
    name: 'ZUNO JIN BRANCO ROSA',
    tagline: 'FLUIDEZ EM MOVIMENTO.',
    price: 189.90,
    description: 'Óculos esportivo máscara Jin com lentes branco/rosa. Estilo e performance para atletas que querem se destacar.',
    features: ['Lentes Branco Rosa', 'Ultra Leve', 'Ventilação Avançada', 'Grip Premium'],
    image: `${IMG}Jin BrancoRosa.webp`,
    category: 'performance',
    variants: [
      { color: '#f9a8d4', colorName: 'Branco Rosa', image: `${IMG}Jin BrancoRosa.webp` },
    ],
    stock: 3,
  },
  {
    id: 'zuno-jin-branco-azul-claro',
    name: 'ZUNO JIN BRANCO AZUL CLARO',
    tagline: 'FLUIDEZ EM MOVIMENTO.',
    price: 189.90,
    description: 'Óculos esportivo máscara Jin com lentes branco/azul claro. Ideal para treinos ao ar livre com proteção total.',
    features: ['Lentes Branco Azul Claro', 'Ultra Leve', 'Ventilação Avançada', 'Grip Premium'],
    image: `${IMG}Jin  Branco Azul Claro.webp`,
    category: 'performance',
    variants: [
      { color: '#bfdbfe', colorName: 'Branco Azul Claro', image: `${IMG}Jin  Branco Azul Claro.webp` },
    ],
    stock: 2,
  },
  {
    id: 'zuno-kansas-marrom-preto',
    name: 'ZUNO KANSAS MARROM PRETO',
    tagline: 'FORÇA DOS DEUSES.',
    price: 169.90,
    description: 'Óculos retangular Kansas Premium 3.0 com lentes marrom preto em metal. Acabamento premium para quem exige o melhor.',
    features: ['Lentes Marrom Preto', 'Armação Metal', 'Proteção UV400', 'Acabamento Premium'],
    image: `${IMG}Kansas Premium 3.0  Marrom Preto.webp`,
    category: 'performance',
    variants: [
      { color: '#92400e', colorName: 'Marrom Preto', image: `${IMG}Kansas Premium 3.0  Marrom Preto.webp` },
    ],
    isNew: true,
    stock: 2,
  },
  // === LINHA LIFESTYLE ===
  {
    id: 'zuno-ares-preto',
    name: 'ZUNO ARES PRETO',
    tagline: 'CORTE PRECISO.',
    price: 169.90,
    description: 'Óculos premium Ares com armação metal preto. Linhas geométricas e design minimalista para quem valoriza estilo.',
    features: ['Design Minimalista', 'Armação Metal', 'Proteção UV400', 'Lentes Escuras'],
    image: `${IMG}Ares Premium  Preto.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#1a1a1a', colorName: 'Preto', image: `${IMG}Ares Premium  Preto.webp` },
    ],
    isNew: true,
    stock: 3,
  },
  {
    id: 'zuno-verona-preto',
    name: 'ZUNO VERONA PRETO',
    tagline: 'SOMBRA URBANA.',
    price: 169.90,
    description: 'Óculos redondo blogueira Verona com armação metal preto. Estilo urbano clássico com proteção total.',
    features: ['Formato Redondo', 'Armação Metal', 'Proteção UV400', 'Lentes Escuras'],
    image: `${IMG}Verona Preto.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#1a1a1a', colorName: 'Preto', image: `${IMG}Verona Preto.webp` },
    ],
    stock: 3,
  },
  {
    id: 'zuno-lorena-azul',
    name: 'ZUNO LORENA AZUL',
    tagline: 'GOLPE DE ESTILO.',
    price: 169.90,
    description: 'Óculos maxi quadrado blogueira Lorena com lentes azul em acetato. Presença marcante para qualquer ocasião.',
    features: ['Formato Maxi Quadrado', 'Lentes Azul', 'Armação Acetato', 'Proteção UV400'],
    image: `${IMG}Lorena  Azul.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#2563eb', colorName: 'Azul', image: `${IMG}Lorena  Azul.webp` },
    ],
    stock: 3,
  },
  {
    id: 'zuno-lorena-preto-degrade',
    name: 'ZUNO LORENA PRETO DEGRADÊ',
    tagline: 'GOLPE DE ESTILO.',
    price: 169.90,
    description: 'Óculos maxi quadrado blogueira Lorena com lentes preto degradê branco em acetato. Elegância e atitude.',
    features: ['Formato Maxi Quadrado', 'Lentes Preto Degradê Branco', 'Armação Acetato', 'Proteção UV400'],
    image: `${IMG}Lorena Preto Degradê Branco.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#1a1a1a', colorName: 'Preto Degradê Branco', image: `${IMG}Lorena Preto Degradê Branco.webp` },
    ],
    stock: 3,
  },
  {
    id: 'zuno-harper-preto',
    name: 'ZUNO HARPER PRETO',
    tagline: 'VIDA COM ESTILO.',
    price: 169.90,
    description: 'Óculos maxi hexagonal blogueira Harper com armação metal preto. Clássico reinventado para o lifestyle urbano.',
    features: ['Formato Maxi Hexagonal', 'Armação Metal', 'Proteção UV400', 'Lentes Escuras'],
    image: `${IMG}Harper  Preto.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#1a1a1a', colorName: 'Preto', image: `${IMG}Harper  Preto.webp` },
    ],
    stock: 4,
  },
  {
    id: 'zuno-hawai-preto-dourado',
    name: 'ZUNO HAWAI PRETO DOURADO',
    tagline: 'BRISA DO PARAÍSO.',
    price: 169.90,
    description: 'Óculos retangular Hawai com armação metal preto dourado. Detalhes dourados para quem vive com estilo.',
    features: ['Detalhes Dourados', 'Armação Metal', 'Proteção UV400', 'Lentes Premium'],
    image: `${IMG}Hawai   Preto Dourado.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#b8860b', colorName: 'Preto Dourado', image: `${IMG}Hawai   Preto Dourado.webp` },
    ],
    isNew: true,
    stock: 3,
  },
  {
    id: 'zuno-diamond-premium-preto-degrade',
    name: 'ZUNO DIAMOND PREMIUM PRETO DEGRADÊ',
    tagline: 'BRILHO ESCURO.',
    price: 169.90,
    description: 'Óculos retangular Diamond Premium com lentes preto degradê injetado. Luxo com atitude para o dia a dia.',
    features: ['Lentes Preto Degradê', 'Armação Injetada', 'Proteção UV400', 'Acabamento Premium'],
    image: `${IMG}Diamond Premium  Preto Degradê.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#1a1a1a', colorName: 'Preto Degradê', image: `${IMG}Diamond Premium  Preto Degradê.webp` },
    ],
    isNew: true,
    stock: 3,
  },
  {
    id: 'zuno-dubai-preto-dourado',
    name: 'ZUNO DUBAI PRETO DOURADO',
    tagline: 'LUXO SEM LIMITES.',
    price: 169.90,
    description: 'Óculos blogueira hexagonal Dubai Premium com armação metal preto dourado/preto. Para quem vive no topo.',
    features: ['Detalhes Dourados', 'Armação Metal', 'Proteção UV400', 'Acabamento Exclusivo'],
    image: `${IMG}Dubai Premium Preto Dourado Preto.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#b8860b', colorName: 'Preto Dourado/Preto', image: `${IMG}Dubai Premium Preto Dourado Preto.webp` },
    ],
    isNew: true,
    stock: 2,
  },
  {
    id: 'zuno-hexagonal-marrom-degrade',
    name: 'ZUNO HEXAGONAL MARROM DEGRADÊ',
    tagline: 'GEOMETRIA PERFEITA.',
    price: 169.90,
    description: 'Óculos redondo hexagonal B 2.0 com lentes marrom degradê em metal. Design icônico para personalidades marcantes.',
    features: ['Formato Hexagonal', 'Lentes Marrom Degradê', 'Armação Metal', 'Design Icônico'],
    image: `${IMG}Hexagonal B 2.0  Marrom Degradê.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#854d0e', colorName: 'Marrom Degradê', image: `${IMG}Hexagonal B 2.0  Marrom Degradê.webp` },
    ],
    stock: 2,
  },
  {
    id: 'zuno-florenca-preto',
    name: 'ZUNO FLORENÇA PRETO',
    tagline: 'FORJADO PARA DURAR.',
    price: 169.90,
    description: 'Óculos redondo Florença 2.0 com armação metal preto. Construção premium para quem exige qualidade e estilo.',
    features: ['Formato Redondo', 'Armação Metal', 'Proteção UV400', 'Alta Resistência'],
    image: `${IMG}Florença 2.0  Preto.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#1a1a1a', colorName: 'Preto', image: `${IMG}Florença 2.0  Preto.webp` },
    ],
    stock: 2,
  },
  {
    id: 'zuno-samba-preto-dourado',
    name: 'ZUNO SAMBA PRETO DOURADO',
    tagline: 'RITMO DOURADO.',
    price: 169.90,
    description: 'Óculos retangular Samba com armação metal preto/dourado. O espírito brasileiro em forma de óculos.',
    features: ['Detalhes Dourados', 'Armação Metal', 'Proteção UV400', 'Design Brasileiro'],
    image: `${IMG}Samba  Preto Dourado.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#b8860b', colorName: 'Preto Dourado', image: `${IMG}Samba  Preto Dourado.webp` },
    ],
    isNew: true,
    stock: 2,
  },
  {
    id: 'zuno-samba-marrom-rose',
    name: 'ZUNO SAMBA MARROM ROSE',
    tagline: 'RITMO DOURADO.',
    price: 169.90,
    description: 'Óculos retangular Samba com lentes marrom degradê rose em metal. Feminilidade e estilo em cada detalhe.',
    features: ['Lentes Marrom Degradê Rose', 'Armação Metal', 'Proteção UV400', 'Design Exclusivo'],
    image: `${IMG}Samba  Marrom Degradê Rose.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#f4a6c0', colorName: 'Marrom Degradê Rose', image: `${IMG}Samba  Marrom Degradê Rose.webp` },
    ],
    isNew: true,
    stock: 2,
  },
  {
    id: 'zuno-samba-marrom-preto',
    name: 'ZUNO SAMBA MARROM PRETO',
    tagline: 'RITMO DOURADO.',
    price: 169.90,
    description: 'Óculos retangular Samba com lentes marrom degradê preto em metal. Sofisticação para o dia a dia.',
    features: ['Lentes Marrom Degradê Preto', 'Armação Metal', 'Proteção UV400', 'Design Exclusivo'],
    image: `${IMG}Samba Marrom Degradê Preto.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#92400e', colorName: 'Marrom Degradê Preto', image: `${IMG}Samba Marrom Degradê Preto.webp` },
    ],
    isNew: true,
    stock: 2,
  },
  {
    id: 'zuno-diamond-preto',
    name: 'ZUNO DIAMOND PRETO',
    tagline: 'ESTILO URBANO.',
    price: 169.90,
    description: 'Óculos blogueira retangular Diamond com armação injetada preto. Estilo discreto com proteção total para o dia a dia.',
    features: ['Armação Injetada', 'Lentes Escuras', 'Proteção UV400', 'Design Urbano'],
    image: `${IMG}Diamond  Preto.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#1a1a1a', colorName: 'Preto', image: `${IMG}Diamond  Preto.webp` },
    ],
    stock: 3,
  },
  {
    id: 'zuno-dune-marrom',
    name: 'ZUNO DUNE MARROM',
    tagline: 'CAMUFLAGEM URBANA.',
    price: 169.90,
    description: 'Óculos redondo clássico Dune com lentes marrom em metal. Estilo atemporal para qualquer ocasião.',
    features: ['Formato Redondo', 'Lentes Marrom', 'Armação Metal', 'Proteção UV400'],
    image: `${IMG}Dune  Marrom.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#92400e', colorName: 'Marrom', image: `${IMG}Dune  Marrom.webp` },
    ],
    stock: 3,
  },
  {
    id: 'zuno-aviador-light-preto',
    name: 'ZUNO AVIADOR LIGHT PRETO',
    tagline: 'ACIMA DAS NUVENS.',
    price: 169.90,
    description: 'Óculos clássico aviador Light com armação metal preto. Visão privilegiada com o estilo atemporal do aviador.',
    features: ['Formato Aviador', 'Armação Metal', 'Proteção UV400', 'Design Clássico'],
    image: `${IMG}Aviador Light  Preto.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#1a1a1a', colorName: 'Preto', image: `${IMG}Aviador Light  Preto.webp` },
    ],
    stock: 4,
  },
  {
    id: 'zuno-mia-rosa-camuflado',
    name: 'ZUNO MIA ROSA CAMUFLADO',
    tagline: 'ENERGIA PURA.',
    price: 169.90,
    description: 'Óculos oval Mia com lentes rosa camuflado em acetato. Cores vibrantes para quem não passa despercebido.',
    features: ['Formato Oval', 'Lentes Rosa Camuflado', 'Armação Acetato', 'Proteção UV400'],
    image: `${IMG}Mia  Rosa Camuflado.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#ec4899', colorName: 'Rosa Camuflado', image: `${IMG}Mia  Rosa Camuflado.webp` },
    ],
    stock: 3,
  },
  {
    id: 'zuno-oregon-rosa-escuro',
    name: 'ZUNO OREGON ROSA ESCURO',
    tagline: 'FOGO NA TRILHA.',
    price: 169.90,
    description: 'Óculos maxi aviador Oregon 2.0 com lentes rosa escuro camuflado em acetato. Para quem quer performance com estilo.',
    features: ['Formato Maxi Aviador', 'Lentes Rosa Escuro Camuflado', 'Armação Acetato', 'Proteção UV400'],
    image: `${IMG}Oregon 2.0  Rosa Escuro Camuflado.webp`,
    category: 'lifestyle',
    variants: [
      { color: '#be185d', colorName: 'Rosa Escuro Camuflado', image: `${IMG}Oregon 2.0  Rosa Escuro Camuflado.webp` },
    ],
    stock: 3,
  },
];
